### Import necessary libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Read the data from the csv file

In [3]:
# read csv
df = pd.read_csv('Life_Expectancy_Data.csv')

In [8]:
# show first 5 rows
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

### Feature information

| Heeader name                    | Description |
| ------------------------------- | ----------- |
| Country                         |             |
| Year                            |             |
| Status                          |             |
| Life expectancy                 |             |
| Adult Mortality                 |             |
| infant deaths                   |             |
| Alcohol                         |             |
| percentage expenditure          |             |
| Hepatitis B                     |             |
| Measles                         |             |
| BMI                             |             |
| under-five deaths               |             |
| Polio                           |             |
| Total expenditure               |             |
| Diphtheria                      |             |
| HIV/AIDS                        |             |
| GDP                             |             |
| Population                      |             |
| thinness 1-19 years             |             |
| thinness 5-9 years              |             |
| Income composition of resources |             |
| Schooling                       |             |

### Number of rows and columns of the DataFrame

In [7]:
# get number of rows
num_rows = df.shape[0]

# get number of columns
num_cols = df.shape[1]

print('Number of rows:', num_rows)
print('Number of columns:', num_cols)

Number of rows: 2938
Number of columns: 22

### Data types of the columns

In [9]:
# get DataFrame info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

### Check duplicates rows

In [10]:
# get number of duplicated rows
duplicated_rows = df.duplicated().sum()

# check if there are duplicated rows
if duplicated_rows > 0:
    print("Number of duplicated rows:", duplicated_rows)
else:
    print("No duplicated rows found")

No duplicated rows found

### Statistical

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,2938.0,2.007519e+03,4.613841e+00,2000.00000,2004.000000,2.008000e+03,2.012000e+03,2.015000e+03
Life expectancy,2928.0,6.922493e+01,9.523867e+00,36.30000,63.100000,7.210000e+01,7.570000e+01,8.900000e+01
Adult Mortality,2928.0,1.647964e+02,1.242921e+02,1.00000,74.000000,1.440000e+02,2.280000e+02,7.230000e+02
infant deaths,2938.0,3.030395e+01,1.179265e+02,0.00000,0.000000,3.000000e+00,2.200000e+01,1.800000e+03
Alcohol,2744.0,4.602861e+00,4.052413e+00,0.01000,0.877500,3.755000e+00,7.702500e+00,1.787000e+01
percentage expenditure,2938.0,7.382513e+02,1.987915e+03,0.00000,4.685343,6.491291e+01,4.415341e+02,1.947991e+04
Hepatitis B,2385.0,8.094046e+01,2.507002e+01,1.00000,77.000000,9.200000e+01,9.700000e+01,9.900000e+01
Measles,2938.0,2.419592e+03,1.146727e+04,0.00000,0.000000,1.700000e+01,3.602500e+02,2.121830e+05
BMI,2904.0,3.832125e+01,2.004403e+01,1.00000,19.300000,4.350000e+01,5.620000e+01,8.730000e+01
under-five deaths,2938.0,4.203574e+01,1.604455e+02,0.00000,0.000000,4.000000e+00,2.800000e+01,2.500000e+03
Polio,2919.0,8.255019e+01,2.342805e+01,3.00000,78.000000,9.300000e+01,9.700000e+01,9.900000e+01
Total expenditure,2712.0,5.938190e+00,2.498320e+00,0.37000,4.260000,5.755000e+00,7.492500e+00,1.760000e+01
Diphtheria,2919.0,8.232408e+01,2.371691e+01,2.00000,78.000000,9.300000e+01,9.700000e+01,9.900000e+01
HIV/AIDS,2938.0,1.742103e+00,5.077785e+00,0.10000,0.100000,1.000000e-01,8.000000e-01,5.060000e+01
GDP,2490.0,7.483158e+03,1.427017e+04,1.68135,463.935626,1.766948e+03,5.910806e+03,1.191727e+05
Population,2286.0,1.275338e+07,6.101210e+07,34.00000,195793.250000,1.386542e+06,7.420359e+06,1.293859e+09
thinness 1-19 years,2904.0,4.839704e+00,4.420195e+00,0.10000,1.600000,3.300000e+00,7.200000e+00,2.770000e+01
thinness 5-9 years,2904.0,4.870317e+00,4.508882e+00,0.10000,1.500000,3.300000e+00,7.200000e+00,2.860000e+01
Income composition of resources,2771.0,6.275511e-01,2.109036e-01,0.00000,0.493000,6.770000e-01,7.790000e-01,9.480000e-01
Schooling,2775.0,1.199279e+01,3.358920e+00,0.00000,10.100000,1.230000e+01,1.430000e+01,2.070000e+01

### Handle missing values

In [14]:
# check missing values
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [16]:
# calculate missing percentage
missing_percentage = df.isnull().mean() * 100
missing_percentage[missing_percentage.values > 0].sort_values(ascending=False)

Population                         22.191967
Hepatitis B                        18.822328
GDP                                15.248468
Total expenditure                   7.692308
Alcohol                             6.603131
Income composition of resources     5.684139
Schooling                           5.547992
 BMI                                1.157250
 thinness  1-19 years               1.157250
 thinness 5-9 years                 1.157250
Polio                               0.646698
Diphtheria                          0.646698
Life expectancy                     0.340368
Adult Mortality                     0.340368
dtype: float64

In [24]:
%%capture
# filling the missing values with the mean of the column.
df = df.fillna(df.mean())

In [25]:
# check missing values again
df.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64